#!/bin/sh
cd `rpm --eval %{_builddir}`

# This script reads filenames from STDIN and outputs any relevant provides
# information that needs to be included in the package.

filelist=$(grep "\\.so" | grep -v "^/lib/ld.so" | xargs file -L 2>/dev/null | grep "ELF.*shared object" | cut -d: -f1)
if [ -f __rpm_noautoprovfiles ] ; then
	for i in `cat __rpm_noautoprovfiles`; do
		filelist=`echo $filelist | sed "s![[:space:]]*$i[[:space:]]*!!g"`
	done
fi

allprovides=`for f in $filelist; do
    soname=$(objdump -p $f | awk '/SONAME/ {print $2}')

    if [ "$soname" != "" ]; then
        if [ ! -L $f ]; then
            echo $soname
	    objdump -p $f | awk '
		BEGIN { START=0 ; }
		/Version definitions:/ { START=1; }
		/^[0-9]/ && (START==1) { print $4; }
		/^$/ { START=0; }
	    ' | \
		grep -v $soname | \
		while read symbol ; do
		    echo "$soname($symbol)"
		done
	fi
    else
	echo ${f##*/}
    fi
done | sort -u`

if [ -f __rpm_noautoprovdep ] ; then
	for i in `cat __rpm_noautoprovdep`; do
		allprovides=`echo $allprovides | sed "s!\<$i[[:space:]]*!!g"`
	done
fi

echo "$allprovides"


