#!/bin/sh
# add rpm's obscured capabilities to rpm package

filelist=`sed "s/['\"]/\\\&/g" | sed 's/^[[:space:]]*//g'`
echo $filelist | /usr/lib/rpm/find-provides

LOG=/tmp/logg

for f in $filelist; do 
    RPM=`echo $f | awk '/\/bin\/rpm$/ { print }'`
    if [ ! -z $RPM ]; then
	break
    fi
done

if [ -z $RPM ]; then
    exit 0;
fi

if [ ! -x $RPM ]; then
    exit 1
fi

$RPM --rcfile="" --showrc | pgrep 'rpmlib\(.*?\)' | sed 's/^[[:space:]]*//g'

