#!/bin/sh
ulimit -c 0
cd `rpm --eval %{_builddir}`

filelist=`sed "s/['\"]/\\\&/g"`
if [ -f __rpm_noautoreqfiles ] ; then
	for i in `cat __rpm_noautoreqfiles`; do
		filelist=`echo $filelist | sed "s![[:space:]]*$i[[:space:]]*!!g"`
	done
fi

requires="`echo $filelist|/usr/lib/rpm/find-requires`"
requires_perl="`/usr/lib/rpm/perl.req $filelist`"

eval "`perl -V:installsitearch`"
if [ -n "`echo $filelist | grep $installsitearch`" ] ; then
        requires_perlarch="$installsitearch `LC_ALL="C" rpm -q --queryformat '%{NAME} = %{VERSION}' perl| grep -v "is not"`"
fi

if [ -f __rpm_noautoreq ] ; then
	for i in `cat __rpm_noautoreq`; do
		requires_perl=`echo $requires_perl | sed "s!\<$i[[:space:]]*!!g"`
	done
fi

requires_perl_t="$requires_perl"
if [ -f __rpm_noautoreqdep ] ; then
	for i in `cat __rpm_noautoreqdep`; do
		requires_perl_t=`echo $requires_perl_t | sed "s!\<$i[[:space:]]*!!g"`
	done
fi

requires_mod="`LC_ALL=C rpm -q --whatprovides --qf "%{NAME}\n"  $requires_perl_t 2>/dev/null`"
echo "$requires
$requires_perl
$requires_perlarch
$requires_mod"| grep -v "no package provides" | sort -u
