#!/bin/sh
cd `rpm --eval %{_builddir}`

# This script reads filenames from STDIN and outputs any relevant provides
# information that needs to be included in the package.

filelist=$(grep "\\.so" | grep -v "^/lib/ld.so" | xargs file -L 2>/dev/null | grep "ELF.*shared object" | cut -d: -f1)
if [ -f __rpm_noautoprovfiles ] ; then
	for i in `cat __rpm_noautoprovfiles`; do
		filelist=`echo $filelist | sed "s![[:space:]]*$i[[:space:]]*!!g"`
	done
fi

case `uname -m` in
    alpha*)       mark64="" ;;
    *)            mark64="()(64bit)" ;;
esac
    
allprovides=`for f in $filelist; do
    soname=$(objdump -p $f 2> /dev/null | awk '/SONAME/ {print $2}')

    lib64=`if file -L $f 2>/dev/null | \
    	grep "ELF 64-bit" >/dev/null; then echo "$mark64"; fi`
	
    if [ "$soname" != "" ]; then
        if [ ! -L $f ]; then
            echo $soname$lib64
	    objdump -p $f 2> /dev/null | awk '
		BEGIN { START=0 ; }
		/Version definitions:/ { START=1; }
		/^[0-9]/ && (START==1) { print $4; }
		/^$/ { START=0; }
	    ' | \
		grep -v $soname | \
		while read symbol ; do
		    echo "$soname($symbol)`echo $lib64 | sed 's/()//'`"
		done
	fi
    else
	echo ${f##*/}$lib64
    fi
done | sort -u`

if [ -f __rpm_noautoprov ] ; then
	for i in `cat __rpm_noautoprov`; do
		allprovides=`echo $allprovides | sed "s!\<$i[[:space:]]*!!g"`
	done
fi

echo "$allprovides"


