#!/bin/sh
ulimit -c 0
cd `rpm --eval %{_builddir}`

filelist=`sed "s/['\"]/\\\&/g"`
if [ -f __rpm_noautoprovfiles ] ; then
	for i in `cat __rpm_noautoprovfiles`; do
		filelist=`echo $filelist | sed "s![[:space:]]*$i[[:space:]]*!!g"`
	done
fi


echo $filelist|/usr/lib/rpm/find-provides
provides_perl=`/usr/lib/rpm/perl.prov $filelist`
if [ -f __rpm_noautoprov ] ; then
	for i in `cat __rpm_noautoprov`; do
		provides_perl=`echo $provides_perl | sed "s!\<$i[[:space:]]*!!g"`
	done
fi

echo "$provides_perl"
