#!/bin/sh
umask 022
export GCONF_CONFIG_SOURCE="xml:readwrite:/etc/gconf/gconf.xml.defaults"
if [ $# -gt 0 ] ; then
    /usr/bin/gconftool-2 --makefile-install-rule \
    "$@" > /dev/null 
else
    /usr/bin/gconftool-2 --makefile-install-rule \
    /etc/gconf/schemas/*.schemas > /dev/null 
fi
